### PR TITLE
Added package.json.

### PR DESCRIPTION
**Pull request by apexskier**
Allows installation with npm, for non global use (in my case).

### CODE REVIEW

**Comment by ironwallaby** [comment]
Marking WNF.

I'm not sure why this would be desirable: my understanding was that NPM is for Node.JS, and Skycons is strictly a browser-only project. (That is, it doesn't really make sense on the backend.)

Also, there won't be any Javascript left in this project at all once #11 is complete, so it will be even less relevant then.

**Comment by jisaacks** [comment]
@ironwallaby NPM is **NOT** just for Node.js, it is very much for ALL JavaScript packages. It was originally for node but their scope as changed. 

Even if you are no longer using any JavaScript, it is still a very good idea to include a package.json. For example, [normalize.css](https://github.com/necolas/normalize.css/) a ~20K stars repo has zero javascript and includes a package.json and many people use NPM to install it.

You may not need a package.json for your use case and that it is fine, adding one won't hurt those that do not need it. But not having one prevents anyone from being able to install this with NPM, then if someone needs to be able to install with NPM they would need to maintain a fork simple to add a package.json file.

You do not even have to manage deployments to npm, as long as your project has a package.json, people can install directly from github via `npm install darkskyapp/skycons` but this will not work if you do not have a package.json

There really is no reason not to have one.

**Comment by ironwallaby** [comment]
Even if I allow that NPM is useful for non-Node JavaScript packages, it seems to me a slippery slope to support this given that it's an explicit goal to _remove all JavaScript from this project_. At that point, what's to stop requests of supporting every, single package manager that exists? The only reasonable line-in-the-sand I can draw is "support the package managers that are useful to me," in which case the answer is "none."

Furthermore, I _really don't understand_ the notion of _installing_ content. For example, you don't _install_ `normalize.css`: it's not a computer program! Sure, you can use NPM to _download_ it for you, but I don't see how this is meaningfully different or better than using Git to download it. After all, this is the very thing that Git was designed for! (I will gladly allow that maybe I'm old-school or brain-damaged or _something,_ but I simply don't understand the use-case.)

I'm really, terribly sorry that this isn't a helpful answer to you, but this goal of this project isn't to be all things to all people: it's to make something that I have made for my own use to be available to others, on the off chance that they, too, find it useful. I'm not explicitly here to support open source as a movement: I'm here to make nifty things. If others like that, great! But it strikes me as disingenuous (and dangerous to my own well-being!) to spend my scant free time doing things that I don't want to do in order to support use-cases I don't understand. This is part of the reason why I've made the license of this project _as permissible as legally possible_: if you don't like the way I manage the project, _please feel free to fork it with my blessings_. My feelings will not be hurt and I will even point people your way. <3

**Comment by shehi** [comment]
However unbaked your ideas about NPM was, please reopen and merge this PR, as NPM is used with countless number of packaging systems, including Webpack. This package must have NPM support, otherwise you better just delete this repo.

**Pull request closed without merging**
